// End-to-end booking in demo-payment mode. Usage: node scripts/e2e-booking.mjs [baseUrl] [width]
import { chromium } from 'playwright';
const base = process.argv[2] ?? 'http://localhost:3000';
const width = Number(process.argv[3] ?? 390);
const shot = (p, n) => p.screenshot({ path: `screenshots/booking-${n}-${width}.png` });
const b = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const c = await b.newContext({ viewport: { width, height: width < 800 ? 844 : 900 } });
const host = new URL(base).hostname;
await c.addCookies([{ name: 'vicelic_age', value: '1', domain: host, path: '/' }, { name: 'vicelic_consent', value: 'necessary', domain: host, path: '/' }]);
const p = await c.newPage();
const t0 = Date.now();
await p.goto(`${base}/en/experience#book=the-slope`, { waitUntil: 'networkidle' });
await p.waitForTimeout(600);
await shot(p, '1-widget');
// first open day
const day = p.locator('#book button[aria-pressed]:not([disabled])').first();
await day.click();
await p.waitForTimeout(300);
await p.locator('#book input[name="time"]:not([disabled])').first().locator('..').click();
await p.getByRole('button', { name: 'Adults +' }).first().click();
await p.getByRole('button', { name: 'Children +' }).first().click();
await p.waitForTimeout(300);
await shot(p, '2-selected');
await p.fill('#f-name', 'Jane Traveller');
await p.fill('#f-email', 'jane@example.com');
await p.fill('#f-phone', '+1 555 0100');
await p.fill('#f-notes', 'No shellfish, please.');
await p.locator('input[name="terms"]').check();
await p.locator('#book form button[type="submit"]').scrollIntoViewIfNeeded();
await shot(p, '3-details');
await p.locator('#book form button[type="submit"]').click();
await p.waitForURL(/checkout/);
await p.waitForTimeout(500);
await shot(p, '4-checkout');
await p.getByRole('button', { name: /Pay .* \(demo\)/ }).click();
await p.waitForURL(/booked/);
await p.waitForTimeout(800);
console.log('booked in', ((Date.now() - t0) / 1000).toFixed(1), 's →', p.url());
await shot(p, '5-confirmed');
const ics = await p.request.get(await p.locator('a', { hasText: 'Add to calendar' }).getAttribute('href').then((h) => base + h));
console.log('ics', ics.status(), (await ics.text()).split('\r\n').filter((l) => /^(DTSTART|DTEND|SUMMARY|LOCATION)/.test(l)).join(' | '));
await b.close();
