// End-to-end purchase in demo-payment mode. Usage: node scripts/e2e-shop.mjs [baseUrl] [width]
import { chromium } from 'playwright';
const base = process.argv[2] ?? 'http://localhost:3000';
const width = Number(process.argv[3] ?? 390);
const shot = (p, n, full = false) => p.screenshot({ path: `screenshots/shop-${n}-${width}.png`, fullPage: full });
const b = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const c = await b.newContext({ viewport: { width, height: width < 800 ? 844 : 900 } });
const host = new URL(base).hostname;
await c.addCookies([{ name: 'vicelic_age', value: '1', domain: host, path: '/' }, { name: 'vicelic_consent', value: 'necessary', domain: host, path: '/' }]);
const p = await c.newPage();
await p.goto(`${base}/en/wines`, { waitUntil: 'networkidle' });
await p.evaluate(() => document.querySelectorAll('.reveal').forEach((el) => el.setAttribute('data-visible', 'true')));
await p.waitForTimeout(1200);
await shot(p, '1-list', true);
await p.goto(`${base}/en/wines/dingac`, { waitUntil: 'networkidle' });
await p.getByText('Case of 6').click();
await p.waitForTimeout(400);
await shot(p, '2-product');
await p.getByRole('button', { name: /Add to cart/ }).click();
await p.goto(`${base}/en/wines/gift-box`, { waitUntil: 'networkidle' });
await p.getByRole('button', { name: /Add to cart/ }).click();
await p.goto(`${base}/en/shop/cart`, { waitUntil: 'networkidle' });
await p.waitForTimeout(500);
await shot(p, '3-cart', true);
await p.selectOption('#c-country', 'US').catch(() => p.selectOption('#c-country', 'OTHER'));
await p.waitForTimeout(300);
await shot(p, '4-not-available');
await p.selectOption('#c-country', 'HR');
await p.fill('#c-name', 'Ivana Horvat');
await p.fill('#c-email', 'ivana@example.com');
await p.fill('#c-phone', '+385 91 123 4567');
await p.fill('#c-street', 'Ilica 1');
await p.fill('#c-postal', '10000');
await p.fill('#c-city', 'Zagreb');
await p.locator('input[name="terms"]').check();
await p.getByRole('button', { name: /Pay .* securely/ }).click();
await p.waitForURL(/shop\/checkout/);
await p.getByRole('button', { name: /\(demo\)/ }).click();
await p.waitForURL(/ordered/);
await p.waitForTimeout(800);
await shot(p, '5-ordered');
const count = await p.evaluate(() => localStorage.getItem('vicelic_cart'));
console.log('ordered →', p.url(), '| cart after:', count);
await b.close();
